### ISSUE TITLE
Existing solutions

### ISSUE THREAD

**Issue by lauriro** [sebastien/domish.js#1]
Have you tried existing solutions, like mine: [litejs/dom](https://github.com/litejs/dom)?
I'd love to hear about its limitations that led you to create another one.

**Comment by sebastien** [comment]
What I had in mind was:
- compact
- pure JavaScript (no transpiler/build step)
- ESM-modules only
- hackable 

The non goals were:
- full conformance
- high performance

LiteDOM looks great, I would have probably tried it before strarting domish if it had ESM modules and a class-based implementation.

**Comment by lauriro** [comment]
For a library I will prefer CommonJS style for while.
Only ESM projects can import ES modules, while CommonJS modules can be used in both ESM and CommonJS projects.
